### ISSUE TITLE
How to use the APIs for the services in the OpenLMIS?

### ISSUE THREAD

**Issue by AdityaKBhadragond14** [OpenLMIS/openlmis-ref-distro#131]
I want to use the APIs from the services in the OpenLMIS to integrate it in my mobile application. Where can I find these APIs? It would be really helpful if someone can answer my question ASAP. Thank You.

**Comment by AdityaKBhadragond14** [comment]
Can I get the answer to my question ASAP.

**Comment by anawrotsoldevelo** [comment]
You can access available endpoints on:
http://docs.openlmis.org/en/latest/components/index.html#logging-into-the-live-documentation

Under every service there is a link to documentation for an API

**Comment by AdityaKBhadragond14** [comment]
Thank You.
